<?php
/**
 * Installs the dev probes as a must-use plugin.
 *
 *   docker compose exec wpcli wp eval-file /tools/dev-probes/install.php
 *
 * Writes a one-line mu-plugin that requires the loader from the /tools mount. The probes
 * themselves stay in the repo — this only wires them in, and only in this local dev
 * container.
 */

defined( 'ABSPATH' ) || die( 'wp eval-file only' );

$mu_dir = WPMU_PLUGIN_DIR;

if ( ! is_dir( $mu_dir ) && ! wp_mkdir_p( $mu_dir ) ) {
	WP_CLI::error( "cannot create {$mu_dir}" );
}

$file = $mu_dir . '/hrd-dev-probes.php';

$contents = <<<'PHP'
<?php
/**
 * Plugin Name: HR Design — dev probes
 * Description: Loads the audit probes from the /tools mount. Local development only.
 *
 * Generated by tools/dev-probes/install.php. Not part of the theme, not for deployment.
 */

defined( 'ABSPATH' ) || exit;

if ( defined( 'WP_DEBUG' ) && WP_DEBUG && file_exists( '/tools/dev-probes/loader.php' ) ) {
	require_once '/tools/dev-probes/loader.php';
}
PHP;

if ( false === file_put_contents( $file, $contents ) ) {
	WP_CLI::error( "cannot write {$file}" );
}

WP_CLI::success( "dev probes installed at {$file}" );
WP_CLI::log( '' );
WP_CLI::log( 'available:' );
WP_CLI::log( '  /?hrd_a11y=1                 accessibility panel on any page' );
WP_CLI::log( '  /?hrd_probe=enqueue          what is enqueued and who pulled it in' );
WP_CLI::log( '  /?hrd_probe=backdrop         photo backdrop luminance distribution' );
WP_CLI::log( '  /?hrd_probe=sheet            contact sheet of studio-classified products' );
WP_CLI::log( '  /?hrd_probe=scenes           contact sheet of room photography' );
WP_CLI::log( '  /?hrd_probe=pick&src=6623    one product, with a 10% grid for hotspots' );
