<?php
/**
 * Installs the composed scene as an hrd_room_scene post.
 *
 *   docker compose exec wpcli wp eval-file /tools/scene/install.php
 *
 * The layers are SVG. That is deliberate: they are flat illustrated planes carrying
 * embedded product cut-outs, so SVG keeps them sharp at any width and the whole scene is
 * ~800KB rather than three 1600px PNGs. SVG uploads stay blocked for everyone except
 * this script, which writes the attachment directly.
 *
 * Idempotent: re-running replaces the layers and hotspots on the same post.
 */

defined( 'ABSPATH' ) || die( 'wp eval-file only' );

require_once ABSPATH . 'wp-admin/includes/image.php';
require_once ABSPATH . 'wp-admin/includes/file.php';

/*
 * Allow SVG for the duration of THIS SCRIPT ONLY.
 *
 * SVG upload is blocked by default for a real reason — an SVG is a document and can
 * carry script. That reason does not apply here: these files are generated by
 * tools/scene/compose.mjs from our own template, never uploaded by a user. The filter is
 * added on the CLI path and never registered in the theme, so the site's upload policy
 * is unchanged.
 */
add_filter(
	'upload_mimes',
	function ( $mimes ) {
		$mimes['svg'] = 'image/svg+xml';
		return $mimes;
	}
);

add_filter(
	'wp_check_filetype_and_ext',
	function ( $data, $file, $filename ) {
		if ( str_ends_with( $filename, '.svg' ) ) {
			$data['ext'] = 'svg';
			$data['type'] = 'image/svg+xml';
		}
		return $data;
	},
	10,
	3
);

$scene_dir = '/seed/scene';
$hotspots_raw = json_decode( file_get_contents( "{$scene_dir}/hotspots.json" ), true );

if ( ! $hotspots_raw ) {
	WP_CLI::error( 'no hotspots.json — run tools/scene/compose.mjs first' );
}

$id_map = json_decode( file_get_contents( '/seed/id-map.json' ), true );

/**
 * Sideload one SVG layer.
 *
 * @param string $file  Path on disk.
 * @param string $title Attachment title.
 * @return int|null
 */
function hrd_install_layer( $file, $title ) {
	if ( ! file_exists( $file ) ) {
		return null;
	}

	// Replace rather than accumulate on re-run.
	$existing = get_posts(
		array(
			'post_type'   => 'attachment',
			'meta_key'    => '_hrd_scene_layer',
			'meta_value'  => basename( $file ),
			'numberposts' => 1,
			'fields'      => 'ids',
		)
	);
	foreach ( $existing as $old ) {
		wp_delete_attachment( $old, true );
	}

	$upload = wp_upload_bits( basename( $file ), null, file_get_contents( $file ) );
	if ( ! empty( $upload['error'] ) ) {
		WP_CLI::warning( $upload['error'] );
		return null;
	}

	$attachment_id = wp_insert_attachment(
		array(
			'post_mime_type' => 'image/svg+xml',
			'post_title'     => $title,
			'post_status'    => 'inherit',
		),
		$upload['file']
	);

	if ( is_wp_error( $attachment_id ) ) {
		return null;
	}

	// SVG has no intrinsic raster metadata; WP is fine with an empty set here.
	wp_update_attachment_metadata( $attachment_id, array( 'width' => 1600, 'height' => 900, 'file' => $upload['file'] ) );
	update_post_meta( $attachment_id, '_hrd_scene_layer', basename( $file ) );
	update_post_meta( $attachment_id, '_wp_attachment_image_alt', $title );

	return $attachment_id;
}

$scene = get_posts(
	array( 'post_type' => 'hrd_room_scene', 'posts_per_page' => 1, 'fields' => 'ids', 'post_status' => 'any' )
);

$scene_id = $scene
	? $scene[0]
	: wp_insert_post(
		array(
			'post_type'   => 'hrd_room_scene',
			'post_title'  => 'המבואה',
			'post_status' => 'publish',
		)
	);

if ( is_wp_error( $scene_id ) ) {
	WP_CLI::error( $scene_id->get_error_message() );
}

$layers = array(
	'bg'   => hrd_install_layer( "{$scene_dir}/layer-bg.svg", 'המבואה — רקע' ),
	'mid'  => hrd_install_layer( "{$scene_dir}/layer-mid.svg", 'המבואה — אמצע' ),
	'fore' => hrd_install_layer( "{$scene_dir}/layer-fore.svg", 'המבואה — חזית' ),
);

// The portrait re-composition — a separate layout, not a crop of the wide one.
$layers_mobile = array(
	'bg'   => hrd_install_layer( "{$scene_dir}/layer-bg-mobile.svg", 'המבואה — רקע (נייד)' ),
	'mid'  => hrd_install_layer( "{$scene_dir}/layer-mid-mobile.svg", 'המבואה — אמצע (נייד)' ),
	'fore' => hrd_install_layer( "{$scene_dir}/layer-fore-mobile.svg", 'המבואה — חזית (נייד)' ),
);

foreach ( $layers as $key => $attachment_id ) {
	if ( $attachment_id ) {
		update_post_meta( $scene_id, "_hrd_layer_{$key}", $attachment_id );
	}
}

foreach ( $layers_mobile as $key => $attachment_id ) {
	if ( $attachment_id ) {
		update_post_meta( $scene_id, "_hrd_layer_{$key}_mobile", $attachment_id );
	}
}

// The bg layer carries the room itself, so it doubles as the featured image and the
// hero fallback.
if ( $layers['bg'] ) {
	set_post_thumbnail( $scene_id, $layers['bg'] );
}

// Map the composer's live ids onto local product ids.
$hotspots = array();
foreach ( $hotspots_raw as $i => $spot ) {
	$src = $spot['product_src_id'] ?? 0;
	if ( ! isset( $id_map[ $src ] ) ) {
		WP_CLI::warning( "src {$src} not imported — hotspot skipped" );
		continue;
	}

	$hotspots[] = array(
		'id'         => 'h' . ( $i + 1 ),
		'x_d'        => (float) $spot['x_d'],
		'y_d'        => (float) $spot['y_d'],
		'x_m'        => (float) $spot['x_m'],
		'y_m'        => (float) $spot['y_m'],
		'layer'      => $spot['layer'],
		'product_id' => (int) $id_map[ $src ],
	);
}

update_post_meta( $scene_id, '_hrd_hotspots', wp_json_encode( $hotspots ) );

WP_CLI::success( sprintf( 'scene %d "%s": %d layers, %d hotspots.', $scene_id, get_the_title( $scene_id ), count( array_filter( $layers ) ), count( $hotspots ) ) );

foreach ( $hotspots as $spot ) {
	WP_CLI::log( sprintf( '  %-5s %5.1f,%5.1f  %s', $spot['layer'], $spot['x_d'], $spot['y_d'], get_the_title( $spot['product_id'] ) ) );
}
