/**
 * Self-hosts the webfonts and generates src/css/base/fonts.css.
 *
 * All four families are OFL. Run once:  node tools/fonts.mjs
 *
 * Google's CSS already splits each family into hebrew / latin / latin-ext blocks with
 * correct unicode-ranges. We keep those blocks verbatim and only rewrite the URLs to
 * local files — hand-writing the ranges is how you end up shipping a Hebrew-only file
 * and rendering every price in Arial.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
// Inside src/ so Vite resolves, hashes and copies them. Left in assets/ they stay
// unresolved at build time and 404 at runtime.
const OUT_FONTS = join(ROOT, 'theme', 'src', 'fonts');
const OUT_CSS = join(ROOT, 'theme', 'src', 'css', 'base', 'fonts.css');

// A modern UA gets woff2 back. An old one gets ttf — hence the pin.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FONTS = [
	{ slug: 'karantina', css: 'family=Karantina:wght@300', subsets: ['hebrew', 'latin'] },
	{ slug: 'assistant', css: 'family=Assistant:wght@400;600', subsets: ['hebrew', 'latin'] },
	{ slug: 'frank-ruhl', css: 'family=Frank+Ruhl+Libre:wght@400', subsets: ['hebrew', 'latin'] },
	// Mono never renders Hebrew — it is measurements only, so Latin is the whole job.
	{ slug: 'plex-mono', css: 'family=IBM+Plex+Mono:wght@400', subsets: ['latin'] },
];

const HEADER = `/*
 * Self-hosted webfonts. GENERATED by tools/fonts.mjs — do not edit by hand.
 *
 * Not the Google CDN: one extra RTT on the LCP path plus the GDPR question, for zero
 * benefit. The unicode-range blocks come from Google's own CSS, so the browser only
 * downloads the Hebrew file for Hebrew text and the Latin file for prices and SKUs.
 */

`;

// Karantina is condensed: an unmatched FOUT reflow is violent, so the fallback is
// metric-adjusted to keep the swap from moving the page.
const FALLBACK = `
@font-face {
	font-family: 'Karantina Fallback';
	src: local('Arial Hebrew'), local('Arial');
	size-adjust: 78%;
	ascent-override: 90%;
	descent-override: 22%;
}
`;

async function main() {
	await mkdir(OUT_FONTS, { recursive: true });
	let out = HEADER;
	let total = 0;

	for (const font of FONTS) {
		const url = `https://fonts.googleapis.com/css2?${font.css}&subset=${font.subsets.join(',')}&display=swap`;
		let css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

		// Google labels each block with a /* subset */ comment above it.
		const blocks = [...css.matchAll(/\/\* (\S+) \*\/\s*(@font-face \{[^}]+\})/g)];

		for (const [, subset, block] of blocks) {
			if (!font.subsets.includes(subset)) continue; // skip latin-ext: no European text here

			const remoteUrl = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
			const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? '400';
			if (!remoteUrl) continue;

			const filename = `${font.slug}-${weight}-${subset}.woff2`;
			const buf = Buffer.from(await (await fetch(remoteUrl)).arrayBuffer());
			await writeFile(join(OUT_FONTS, filename), buf);
			total += buf.length;
			console.log(`${filename.padEnd(34)} ${(buf.length / 1024).toFixed(1)}KB`);

			out += block.replace(/url\(https:[^)]+\.woff2\)/, `url('../../fonts/${filename}')`) + '\n\n';
		}
	}

	await writeFile(OUT_CSS, out + FALLBACK);
	console.log(`\nTotal: ${(total / 1024).toFixed(1)}KB across the whole type system.`);
	console.log(`Wrote ${OUT_CSS}`);
}

main().catch((e) => {
	console.error(e.message);
	process.exit(1);
});
